# Generated by Django 6.0.7 on 2026-08-03 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHADOW', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
