# Generated by Django 6.0.7 on 2026-08-08 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHADOW', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='story_scenes/')),
                ('jumpscare', models.BooleanField(default=False)),
                ('jumpscare_image', models.ImageField(blank=True, null=True, upload_to='jumpscares/')),
                ('jumpscare_sound', models.FileField(blank=True, null=True, upload_to='jumpscare_sounds/')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='SHADOW.story')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('story', 'order')},
            },
        ),
    ]
