# Generated by Django 6.0.7 on 2026-08-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHADOW', '0004_storyscene'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='horror_mode',
            field=models.BooleanField(default=False),
        ),
    ]
