# Generated by Django 6.0.7 on 2026-08-09 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHADOW', '0005_story_horror_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyscene',
            name='jumpscare',
        ),
        migrations.RemoveField(
            model_name='storyscene',
            name='jumpscare_sound',
        ),
        migrations.AddField(
            model_name='storyscene',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='story_scene_audio/'),
        ),
        migrations.AddField(
            model_name='storyscene',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storyscene',
            name='is_jumpscare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storyscene',
            name='jumpscare_audio',
            field=models.FileField(blank=True, null=True, upload_to='jumpscare_audio/'),
        ),
        migrations.AddField(
            model_name='storyscene',
            name='reveal_at_word',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='storyscene',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
