# Generated by Django 6.0.7 on 2026-08-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHADOW', '0006_remove_storyscene_jumpscare_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyscene',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='storyscene',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='storyscene',
            name='order',
        ),
        migrations.RemoveField(
            model_name='storyscene',
            name='reveal_at_word',
        ),
    ]
